project_id = "sbhcnilxueqchughpeui"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[functions.fetch-farcaster-stats]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.sign-verdict-claim]
verify_jwt = false

[functions.generate-bloomer]
verify_jwt = false

[functions.bloomer-metadata]
verify_jwt = false

[functions.backfill-bloomer-metadata]
verify_jwt = false

[functions.seed-bloomer-templates]
verify_jwt = false

[functions.fetch-users-by-address]
verify_jwt = false

[functions.save-energy-result]
verify_jwt = false

[functions.fetch-monthly-stats]
verify_jwt = false

[functions.fetch-bloom-price]
verify_jwt = false

[functions.sign-tip]
verify_jwt = false

[functions.process-tip-webhook]
verify_jwt = false
